version: "2.1"
services:
  jobmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME}
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./target/scala-2.12:/opt/engine/bin
      - ./workspace:/opt/engine/workspace

  taskmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME}
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./target/scala-2-12/engine.flink.jar:/opt/engine/engine.flink.jar
      - ./workspace:/opt/engine/workspace
